### ISSUE TITLE
 generative-manim.vercel.app  down 

### ISSUE THREAD

**Issue by KUKARAF** [marcelo-earth/generative-manim#35]
[generative-manim.vercel.app](https://generative-manim.vercel.app/) seems to respond with 500
no obvious way to selfhost. Any streamlit services just point back to the one broken link.

**Comment by Chen-Steve** [comment]
I believe it's back up

**Comment by KUKARAF** [comment]
i understand that selfhosting is being mitigated on purpose for some reason and instead you want people to use your instance? Or was this an accident?
